### PR TITLE
fix: address `console.log` bug

### PR DESCRIPTION
**Pull request by rosmcmahon**
- console.log was not accepting multiple parameters after instantiating Verto
- added bugfix
- added test to confirm this bugfix
- fixed linter errors

### CODE REVIEW

**Review by littledivy — APPROVED** [review]
Thanks! LGTM

**Review by t8 — APPROVED** [review]
Thank you for the addition, @mcmonkeys1!

**Comment by rosmcmahon** [comment]
😊 happy to help

**Review by johnletey — APPROVED** [review]
Absolutely brilliant @mcmonkeys1! Cheers mate 🙌🏻

**Pull request merged**
